// Electron main process. Serves the static web build (apps/web, adapter-static,
// synced into ./build by scripts/sync-web.mjs) over a custom app:// protocol
// and grants the renderer access to WebHID so the existing browser code talks
// to peripherals without modification.
const path = require('node:path');
const fs = require('node:fs');
const { app, BrowserWindow, protocol, net, session, ipcMain } = require('electron');

const DEV_URL = process.env.VITE_DEV_SERVER_URL;
const BUILD_DIR = path.join(__dirname, '..', 'build');
const APP_SCHEME = 'app';
const APP_ORIGIN = `${APP_SCHEME}://openperipherals`;

// Tiling window managers handle window placement themselves - the renderer
// only shows a close button there.
const TILING_WM = /hyprland|sway|i3|bspwm|dwm|awesome|qtile|river|niri|xmonad/i;
const IS_TILING_WM = TILING_WM.test(
	[process.env.XDG_CURRENT_DESKTOP, process.env.XDG_SESSION_DESKTOP, process.env.DESKTOP_SESSION].filter(Boolean).join(':')
);

protocol.registerSchemesAsPrivileged([
	{
		scheme: APP_SCHEME,
		privileges: { standard: true, secure: true, supportFetchAPI: true }
	}
]);

function serveFile(filePath) {
	return net.fetch(`file://${filePath}`);
}

async function handleAppRequest(request) {
	const url = new URL(request.url);
	const pathname = decodeURIComponent(url.pathname);

	// Route requests (no extension) resolve to prerendered pages when they
	// exist, otherwise to the SPA fallback generated by adapter-static.
	if (!path.extname(pathname)) {
		const candidates = [
			path.join(BUILD_DIR, pathname, 'index.html'),
			path.join(BUILD_DIR, pathname + '.html'),
			path.join(BUILD_DIR, 'app.html')
		];
		for (const candidate of candidates) {
			if (fs.existsSync(candidate)) return serveFile(candidate);
		}
		return new Response('Not found', { status: 404 });
	}

	const filePath = path.normalize(path.join(BUILD_DIR, pathname));
	if (!filePath.startsWith(BUILD_DIR)) return new Response('Forbidden', { status: 403 });
	return serveFile(filePath);
}

function setupWebHid() {
	const ses = session.defaultSession;

	ses.on('select-hid-device', (event, details, callback) => {
		event.preventDefault();
		const filters = details.filter ?? [];
		const matches = (device) =>
			filters.some(
				(filter) =>
					(filter.vendorId === undefined || filter.vendorId === device.vendorId) &&
					(filter.productId === undefined || filter.productId === device.productId)
			);
		const device = details.deviceList.find(matches) ?? details.deviceList[0];
		callback(device ? device.deviceId : '');
	});

	ses.setPermissionCheckHandler((_webContents, permission) => permission === 'hid');

	ses.setDevicePermissionHandler((details) => details.deviceType === 'hid');
}

function createWindow() {
	const win = new BrowserWindow({
		width: 1360,
		height: 860,
		frame: false,
		autoHideMenuBar: true,
		title: 'OpenPeripherals',
		webPreferences: {
			contextIsolation: true,
			nodeIntegration: false,
			preload: path.join(__dirname, 'preload.cjs')
		}
	});

	win.on('page-title-updated', (event) => event.preventDefault());

	registerWindowControls(win);

	if (DEV_URL) {
		win.loadURL(DEV_URL.replace(/\/+$/, '') + '/app');
		win.webContents.openDevTools({ mode: 'detach' });
	} else {
		win.loadURL(`${APP_ORIGIN}/app`);
	}

	return win;
}

function registerWindowControls(win) {
	ipcMain.on('win:minimize', () => win.minimize());
	ipcMain.on('win:maximize', () => (win.isMaximized() ? win.unmaximize() : win.maximize()));
	ipcMain.on('win:close', () => win.close());
	ipcMain.handle('win:is-maximized', () => win.isMaximized());
	// Read in the main process: sandboxed preloads have no process.env access.
	ipcMain.handle('win:env', () => ({ isTilingWM: IS_TILING_WM }));

	const sendMaximized = () => {
		if (!win.isDestroyed()) win.webContents.send('win:maximized', win.isMaximized());
	};
	win.on('maximize', sendMaximized);
	win.on('unmaximize', sendMaximized);
}

app.whenReady().then(() => {
	if (!DEV_URL) protocol.handle(APP_SCHEME, handleAppRequest);
	setupWebHid();

	createWindow();

	app.on('activate', () => {
		if (BrowserWindow.getAllWindows().length === 0) createWindow();
	});
});

app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') app.quit();
});
