// Electron main process. Serves the static web build (apps/web, adapter-static,
// synced into ./build by scripts/sync-web.mjs) over a custom app:// protocol
// and grants the renderer access to WebHID so the existing browser code talks
// to peripherals without modification.
const path = require('node:path');
const fs = require('node:fs');
const { app, BrowserWindow, Tray, Menu, protocol, net, session, ipcMain, shell, nativeImage } = require('electron');

const DEV_URL = process.env.VITE_DEV_SERVER_URL;
const BUILD_DIR = path.join(__dirname, '..', 'build');
const ICON_PATH = path.join(__dirname, '..', 'resources', 'icon.png');
const TRAY_ICON_PATH = path.join(__dirname, '..', 'resources', 'tray.png');

/**
 * Load an image from disk and down-scale it if it exceeds maxSize.
 * A 2048x2048 PNG decodes to ~16 MB - sending that raw to the X server
 * hits the 16 MB XCB request limit and crashes the app with
 * "Cannot send request of length 16777248" (see #icon-size-bug).
 * Resizing to 512 (window icon) / 32 (tray) keeps the request well
 * under the limit while still looking sharp on HiDPI.
 */
function loadIcon(iconPath, maxSize) {
	try {
		const img = nativeImage.createFromPath(iconPath);
		if (img.isEmpty()) return iconPath;
		const { width, height } = img.getSize();
		if (maxSize && (width > maxSize || height > maxSize)) {
			// preserve aspect ratio - for tray.png which is 650x350
			const scale = Math.min(maxSize / width, maxSize / height);
			return img.resize({
				width: Math.round(width * scale),
				height: Math.round(height * scale),
				quality: 'best'
			});
		}
		return img;
	} catch {
		return iconPath;
	}
}
const APP_SCHEME = 'app';
const APP_ORIGIN = `${APP_SCHEME}://openperipherals`;
const RELEASES_API = 'https://api.github.com/repos/ge0rg3e/openperipherals/releases/latest';
const TAGS_API = 'https://api.github.com/repos/ge0rg3e/openperipherals/tags';
const RELEASES_URL = 'https://github.com/ge0rg3e/openperipherals/releases';

// Launched with --hidden by the login item / XDG autostart entry: start in the
// tray instead of showing a window.
const START_HIDDEN_FLAG = '--hidden';

// Tiling window managers handle window placement themselves - the renderer
// only shows a close button there.
const TILING_WM = /hyprland|sway|i3|bspwm|dwm|awesome|qtile|river|niri|xmonad/i;
const IS_TILING_WM = TILING_WM.test(
	[process.env.XDG_CURRENT_DESKTOP, process.env.XDG_SESSION_DESKTOP, process.env.DESKTOP_SESSION].filter(Boolean).join(':')
);

let mainWindow = null;
let tray = null;
// Latest GitHub release cache - avoids hammering the API on every dialog open.
let releaseCache = null;
// Set right before a real quit so the window close handler lets it through -
// an ordinary close only hides the window and keeps the app in the tray.
let quitting = false;

if (!app.requestSingleInstanceLock()) {
	// A second instance just focuses the running one (important once an
	// autostart entry can silently keep the app alive).
	app.quit();
}

protocol.registerSchemesAsPrivileged([
	{
		scheme: APP_SCHEME,
		privileges: { standard: true, secure: true, supportFetchAPI: true }
	}
]);

function serveFile(filePath) {
	return net.fetch(`file://${filePath}`);
}

async function handleAppRequest(request) {
	const url = new URL(request.url);
	const pathname = decodeURIComponent(url.pathname);

	// Route requests (no extension) resolve to prerendered pages when they
	// exist, otherwise to the SPA fallback generated by adapter-static.
	if (!path.extname(pathname)) {
		const candidates = [
			path.join(BUILD_DIR, pathname, 'index.html'),
			path.join(BUILD_DIR, pathname + '.html'),
			path.join(BUILD_DIR, 'app.html')
		];
		for (const candidate of candidates) {
			if (fs.existsSync(candidate)) return serveFile(candidate);
		}
		return new Response('Not found', { status: 404 });
	}

	const filePath = path.normalize(path.join(BUILD_DIR, pathname));
	if (!filePath.startsWith(BUILD_DIR)) return new Response('Forbidden', { status: 403 });
	return serveFile(filePath);
}

function setupWebHid() {
	const ses = session.defaultSession;

	ses.on('select-hid-device', (event, details, callback) => {
		event.preventDefault();
		const filters = details.filter ?? [];
		const matches = (device) =>
			filters.some(
				(filter) =>
					(filter.vendorId === undefined || filter.vendorId === device.vendorId) &&
					(filter.productId === undefined || filter.productId === device.productId)
			);
		// On Windows a Razer board exposes 3 interfaces: MI_00/MI_01 (HID
		// keyboard/consumer, names "USB Input Device"/"HID-compliant*") and
		// MI_02 (vendor lighting, name "Razer Huntsman Elite" for PID 0x0226).
		// The old `find()` picked MI_00 (protected boot keyboard) -> feature
		// reports were silently dropped while the web picker lets the user
		// choose MI_02, so desktop appeared "connected but no updates".
		const candidates = details.deviceList.filter(matches);
		candidates.sort((a, b) => {
			const score = (d) => {
				const name = (d.productName || '').toLowerCase();
				// Vendor interface has the real product name; generic names are the boot interfaces
				if (/razer|logitech|redragon|g512|g810|k556|k582|huntsman|blackwidow|blade/.test(name) && !/usb input device|hid-compliant/.test(name)) return 2;
				if (!/usb input device|hid-compliant/.test(name) && name) return 1;
				return 0;
			};
			return score(b) - score(a);
		});
		const device = candidates[0] ?? details.deviceList.find(matches) ?? details.deviceList[0];
		// Debug: helps diagnosing Windows MI routing without needing a Windows machine locally
		try {
			console.log('[hid] filters', JSON.stringify(filters), 'devices', details.deviceList.map((d) => ({ id: d.deviceId, vid: d.vendorId, pid: d.productId, name: d.productName })), 'picked', device ? { id: device.deviceId, name: device.productName } : null);
		} catch {}
		callback(device ? device.deviceId : '');
	});

	ses.setPermissionCheckHandler((_webContents, permission) => permission === 'hid');

	ses.setDevicePermissionHandler((details) => details.deviceType === 'hid');
}

// --- Start at login -------------------------------------------------------

function autostartFilePath() {
	const configHome = process.env.XDG_CONFIG_HOME || path.join(app.getPath('home'), '.config');
	return path.join(configHome, 'autostart', 'openperipherals.desktop');
}

function loginOpts() {
	// Windows/macOS `getLoginItemSettings` must be queried with the same path/args
	// that were used in `setLoginItemSettings`, otherwise it always returns false
	// (the old code queried without args, so the toggle appeared stuck on Windows).
	if (app.isPackaged) return { path: process.execPath, args: [START_HIDDEN_FLAG] };
	return { path: process.execPath, args: [app.getAppPath(), START_HIDDEN_FLAG] };
}

/** OS truth: registry/login item (win+mac) or the autostart file (linux). */
function isLaunchOnBootEnabled() {
	if (process.platform === 'linux') return fs.existsSync(autostartFilePath());
	try {
		return app.getLoginItemSettings(loginOpts()).openAtLogin;
	} catch {
		return false;
	}
}

function applyLaunchOnBoot(enabled) {
	if (process.platform === 'linux') {
		const file = autostartFilePath();
		if (!enabled) {
			fs.rmSync(file, { force: true });
			return;
		}
		fs.mkdirSync(path.dirname(file), { recursive: true });
		// In dev the electron binary needs the app directory as argument.
		const execArgs = app.isPackaged ? '' : ` "${app.getAppPath()}"`;
		fs.writeFileSync(
			file,
			[
				'[Desktop Entry]',
				'Type=Application',
				'Name=OpenPeripherals',
				'Comment=Open-source peripheral configuration suite',
				`Exec="${process.execPath}"${execArgs} ${START_HIDDEN_FLAG}`,
				'Icon=openperipherals',
				'Terminal=false',
				'X-GNOME-Autostart-enabled=true',
				''
			].join('\n')
		);
		return;
	}
	app.setLoginItemSettings({
		openAtLogin: enabled,
		...loginOpts(),
		...(process.platform === 'darwin' ? { openAsHidden: enabled } : {})
	});
}

// --- Update check ---------------------------------------------------------

// The repo-root package.json is the version source of truth: scripts/dist.mjs
// injects it at package time, and in dev (where the packaged value is absent)
// we read the file directly instead of the workspace package.json.
function displayAppVersion() {
	if (!app.isPackaged) {
		try {
			return JSON.parse(fs.readFileSync(path.join(__dirname, '..', '..', '..', 'package.json'), 'utf8')).version;
		} catch {
			// fall through to Electron's own value
		}
	}
	return app.getVersion();
}

function compareVersions(a, b) {
	const pa = String(a).replace(/^v/i, '').split('.').map((x) => parseInt(x, 10) || 0);
	const pb = String(b).replace(/^v/i, '').split('.').map((x) => parseInt(x, 10) || 0);
	for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
		const diff = (pa[i] ?? 0) - (pb[i] ?? 0);
		if (diff !== 0) return diff;
	}
	return 0;
}

function normalizeVersion(name) {
	return String(name).replace(/^v/i, '');
}

async function fetchLatestRelease() {
	const headers = { Accept: 'application/vnd.github+json', 'User-Agent': 'OpenPeripherals-Desktop' };
	let response;
	try {
		response = await net.fetch(RELEASES_API, { headers, signal: AbortSignal.timeout(10000) });
	} catch (err) {
		throw err instanceof Error ? err : new Error(String(err));
	}

	if (response.ok) {
		const data = await response.json();
		if (data?.tag_name) return { latestVersion: normalizeVersion(data.tag_name), url: String(data.html_url ?? RELEASES_URL) };
	}

	// 404 means no *published* release exists yet (the CI only creates
	// releases on tag builds). Fall back to the newest git tag so the check
	// still reports something sensible before the first release.
	const tagsResponse = await net.fetch(`${TAGS_API}?per_page=20`, { headers, signal: AbortSignal.timeout(10000) });
	if (!tagsResponse.ok) throw new Error(`GitHub responded with ${tagsResponse.status}`);
	const tags = await tagsResponse.json();
	const names = (Array.isArray(tags) ? tags : []).map((tag) => String(tag?.name ?? '')).filter(Boolean);
	const newest = names.sort((a, b) => compareVersions(b, a))[0];
	if (!newest) throw new Error('No release published yet');
	return { latestVersion: normalizeVersion(newest), url: RELEASES_URL };
}

async function checkForUpdate() {
	// Serve a fresh-enough result for 10 minutes.
	if (releaseCache && Date.now() - releaseCache.checkedAt < 600000) {
		return { ...releaseCache };
	}
	try {
		const release = await fetchLatestRelease();
		releaseCache = {
			...release,
			upToDate: compareVersions(displayAppVersion(), release.latestVersion) >= 0,
			checkedAt: Date.now()
		};
		return { ...releaseCache };
	} catch (err) {
		return { upToDate: null, latestVersion: null, url: RELEASES_URL, error: err instanceof Error ? err.message : String(err) };
	}
}

// --- Window & tray --------------------------------------------------------

function showMainWindow() {
	if (!mainWindow || mainWindow.isDestroyed()) {
		createWindow();
		return;
	}
	if (mainWindow.isMinimized()) mainWindow.restore();
	mainWindow.show();
	mainWindow.focus();
}

function toggleMainWindow() {
	const visible = mainWindow && !mainWindow.isDestroyed() && mainWindow.isVisible() && !mainWindow.isMinimized();
	if (visible) mainWindow.hide();
	else showMainWindow();
}

function createTray() {
	try {
		tray = new Tray(loadIcon(TRAY_ICON_PATH, 32));
	} catch {
		return; // platform without tray support
	}
	tray.setToolTip('OpenPeripherals');
	tray.on('click', toggleMainWindow);
	rebuildTrayMenu();
}

function rebuildTrayMenu() {
	if (!tray) return;
	tray.setContextMenu(
		Menu.buildFromTemplate([
			{ label: 'Open OpenPeripherals', click: showMainWindow },
			{ type: 'separator' },
			{
				label: 'Start at login',
				type: 'checkbox',
				checked: isLaunchOnBootEnabled(),
				click: (item) => {
					applyLaunchOnBoot(item.checked);
					rebuildTrayMenu();
				}
			},
			{ type: 'separator' },
			{ label: 'Quit OpenPeripherals', click: () => app.quit() }
		])
	);
}

/** True when the OS started us (login item / autostart): boot into the tray. */
function launchedHidden() {
	if (process.argv.includes(START_HIDDEN_FLAG)) return true;
	if (process.platform === 'darwin') {
		try {
			return app.getLoginItemSettings().wasOpenedAtLogin;
		} catch {
			return false;
		}
	}
	return false;
}

function createWindow() {
	const win = new BrowserWindow({
		width: 1360,
		height: 860,
		show: false,
		frame: false,
		autoHideMenuBar: true,
		title: 'OpenPeripherals (Beta)',
		icon: loadIcon(ICON_PATH, 512),
		webPreferences: {
			contextIsolation: true,
			nodeIntegration: false,
			preload: path.join(__dirname, 'preload.cjs')
		}
	});

	mainWindow = win;

	win.once('ready-to-show', () => {
		if (!launchedHidden()) win.show();
	});

	win.on('page-title-updated', (event) => event.preventDefault());

	// Closing the window keeps the app alive in the tray (like Discord or
	// Steam); only the tray menu's Quit ends the process. Without a tray we
	// have to close for real, otherwise the app would become unreachable.
	win.on('close', (event) => {
		if (!quitting && tray && !tray.isDestroyed()) {
			event.preventDefault();
			win.hide();
		}
	});

	const sendMaximized = () => {
		if (!win.isDestroyed()) win.webContents.send('win:maximized', win.isMaximized());
	};
	win.on('maximize', sendMaximized);
	win.on('unmaximize', sendMaximized);

	if (DEV_URL) {
		win.loadURL(DEV_URL.replace(/\/+$/, '') + '/app');
		win.webContents.openDevTools({ mode: 'detach' });
	} else {
		win.loadURL(`${APP_ORIGIN}/app`);
	}

	return win;
}

// Registered exactly once - createWindow() can run again after the window was
// closed and re-opened from the tray, and ipcMain.handle() throws on a
// duplicate channel registration.
function registerIpc() {
	ipcMain.on('win:minimize', () => mainWindow?.minimize());
	ipcMain.on('win:maximize', () => {
		if (!mainWindow) return;
		if (mainWindow.isMaximized()) mainWindow.unmaximize();
		else mainWindow.maximize();
	});
	ipcMain.on('win:close', () => mainWindow?.close());
	ipcMain.handle('win:is-maximized', () => mainWindow?.isMaximized() ?? false);
	// Read in the main process: sandboxed preloads have no process.env access.
	ipcMain.handle('win:env', () => ({ isTilingWM: IS_TILING_WM }));

	// --- Settings / about ---
	ipcMain.handle('app:info', () => ({
		version: displayAppVersion(),
		electron: process.versions.electron,
		chrome: process.versions.chrome,
		platform: process.platform,
		packaged: app.isPackaged
	}));
	ipcMain.handle('app:check-update', () => checkForUpdate());
	// The URL never crosses IPC from the renderer; main only opens what the
	// GitHub API returned.
	ipcMain.on('app:download-update', () => {
		void shell.openExternal(releaseCache?.url ?? RELEASES_URL);
	});
	ipcMain.handle('settings:get-launch-on-boot', () => isLaunchOnBootEnabled());
	ipcMain.handle('settings:set-launch-on-boot', (_event, value) => {
		try {
			applyLaunchOnBoot(Boolean(value));
			rebuildTrayMenu();
			return { ok: true, enabled: isLaunchOnBootEnabled() };
		} catch (err) {
			return {
				ok: false,
				enabled: isLaunchOnBootEnabled(),
				error: err instanceof Error ? err.message : String(err)
			};
		}
	});
}

app.on('second-instance', showMainWindow);

// Fires before the closed windows are torn down, so every real quit path
// (tray menu, window-all-closed without a tray) unblocks the close handler.
app.on('before-quit', () => {
	quitting = true;
});

app.whenReady().then(() => {
	if (!DEV_URL) protocol.handle(APP_SCHEME, handleAppRequest);
	setupWebHid();
	registerIpc();

	createWindow();
	createTray();

	app.on('activate', () => {
		if (BrowserWindow.getAllWindows().length === 0) createWindow();
		else showMainWindow();
	});
});

app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') app.quit();
});
